apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-to-kube-deploy
  labels:
    app: python_to_kube
spec:
  selector:
    matchLabels:
      app: python_to_kube
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python_to_kube
    # pod spec below
    spec:
      containers:
      - name: python-to-kube
        # replace the line below with your own repo
        image: arboramen/python_to_kube:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
